### ISSUE TITLE
undefined local variable or method `dotfile' for #<AwesomePrint::Inspector:0x...>

### ISSUE THREAD

**Issue by olafz** [logstash-plugins/logstash-output-stdout#11]
In our logstash configuration we have a block where - in certain conditions - events are sent to stdout using this configuration:

```
stdout {
  codec => rubydebug
}
```

After the upgrade to logstash 5.4.3 (from 5.4.0), this results in a 

```
[FATAL][logstash.runner          ] An unexpected error occurred! 
```

A workaround is to change the stdout output to
```
stdout {
}
```

So, the problem is in the rubydebug part. The full backtrace is:

```
#<NameError: undefined local variable or method `dotfile' for #<AwesomePrint::Inspector:0xfdf5f3>>

"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:163:in `merge_custom_defaults!'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:50:in `initialize'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:9:in `ai'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.2/lib/logstash/codecs/rubydebug.rb:39:in `encode_default'",
"org/jruby/RubyMethod.java:120:in `call'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.2/lib/logstash/codecs/rubydebug.rb:35:in `encode'",
"/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'",
"org/jruby/RubyArray.java:1613:in `each'",
"/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'",
"/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'",
"/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:15:in `multi_receive'",
"org/jruby/ext/thread/Mutex.java:149:in `synchronize'",
"/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:14:in `multi_receive'",
"/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'",
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:407:in `output_batch'",
"org/jruby/RubyHash.java:1342:in `each'",
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:406:in `output_batch'",
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `worker_loop'",
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:317:in `start_workers'"
```

**Comment by jakelandis** [comment]
@olafz - I am trying to reproduce, but can not. 

What versions of logstash-output-stdout and awesome_print are installed ?

```cat logstash-core/lib/logstash-core/version.rb ```
and
```find vendor -name "logstash-output-stdout*"```
and
```find vendor -name "awesome_print*"```

My relevant results using tar.gz from 5.4.0 -> 5.4.3 and overlaying files via ```tar xfz logstash-5.4.3.tar.gz -C logstash --strip-components=1```

```LOGSTASH_CORE_VERSION = "5.4.3"```
```vendor/bundle/jruby/1.9/gems/logstash-output-stdout-3.1.0```
```vendor/bundle/jruby/1.9/gems/awesome_print-1.7.0 and vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0```


What was your upgrade path ?  (tar/deb/rpm?)

**Comment by olafz** [comment]
@jakelandis In the meantime I upgraded to 5.5.0, but the issue is still there.

I upgraded logstash using the debian package; it's now running `logstash 1:5.5.0-1`. This is the same upgrade path as I used to upgrade from 5.4.0 to 5.4.3.

To answer your questions:

```
$ cat logstash-core/lib/logstash-core/version.rb
# encoding: utf-8

# The version of logstash core gem.
#
# Note to authors: this should not include dashes because 'gem' barfs if
# you include a dash in the version string.

LOGSTASH_CORE_VERSION = "5.5.0"
```

```
$ find vendor -name "logstash-output-stdout*"
vendor/bundle/jruby/1.9/gems/logstash-output-stdout-3.1.1
vendor/bundle/jruby/1.9/gems/logstash-output-stdout-3.1.1/logstash-output-stdout.gemspec
vendor/bundle/jruby/1.9/specifications/logstash-output-stdout-3.1.1.gemspec
```

```
$ find vendor -name "awesome_print*"
vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0
vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print.rb
vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print
vendor/bundle/jruby/1.9/specifications/awesome_print-1.8.0.gemspec
```

Just to be thorough: the backtrace in 5.5.0:

```
#<NameError: undefined local variable or method `dotfile' for #<AwesomePrint::Inspector:0x62782c12>>

"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:163:in `merge_custom_defaults!'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:50:in `initialize'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:9:in `ai'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:39:in `encode_default'",
"org/jruby/RubyMethod.java:120:in `call'",
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:35:in `encode'",
"/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'",
"org/jruby/RubyArray.java:1613:in `each'",
"/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'",
"/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'",
"/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:15:in `multi_receive'",
"org/jruby/ext/thread/Mutex.java:149:in `synchronize'",
"/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:14:in `multi_receive'",
"/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'",
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:420:in `output_batch'",
"org/jruby/RubyHash.java:1342:in `each'",
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:419:in `output_batch'",
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `worker_loop'",
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:330:in `start_workers'"
```

**Comment by jakelandis** [comment]
Hmm... I replicated the same setup in an Ubuntu 14.04 VM, starting at 5.4.0 -> 5.4.3 -> 5.5.0, and still can not reproduce. I have all the same versions as you do above. 

Perhaps the issue only presents itself with specific configuration.  Can you try with my config _```echo "hi" | nc localhost 51115```_  and post yours _minus any sensitive configuration_ ?  

```
input { 
tcp {
    port => 55115
	}
}
filter {}
output { 
  elasticsearch { hosts => ["10.0.0.103:9200"] }
   stdout { 
       codec => rubydebug 
      }
} 
```

**Comment by anjo-swe** [comment]
@jakelandis was able to reproduce it using 5.5.1

Config:
```
input { 
  tcp {
    port => 55115
  }
}

filter { }

output { 
  stdout { 
    codec => rubydebug 
  }
}
```

Pushed in data using:
`echo "hi" | nc localhost 55115`

Log:
```
[2017-08-10T16:59:08,778][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>250}
[2017-08-10T16:59:08,804][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:55115"}
[2017-08-10T16:59:08,817][INFO ][logstash.pipeline        ] Pipeline main started
[2017-08-10T16:59:08,881][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-08-10T17:04:23,512][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NameError: undefined local variable or method `dotfile' for #<AwesomePrint::Inspector:0x37590338>>, :backtrace=>["/opt/ensighten/app/logstash/current/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:163:in `merge_custom_defaults!'", "/opt/ensighten/app/logstash/current/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:50:in `initialize'", "/opt/ensighten/app/logstash/current/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:9:in `ai'", "/opt/ensighten/app/logstash/current/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:39:in `encode_default'", "org/jruby/RubyMethod.java:120:in `call'", "/opt/ensighten/app/logstash/current/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:35:in `encode'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/output_delegator_strategies/single.rb:15:in `multi_receive'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/output_delegator_strategies/single.rb:14:in `multi_receive'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/pipeline.rb:420:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/pipeline.rb:419:in `output_batch'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/pipeline.rb:365:in `worker_loop'", "/opt/ensighten/app/logstash/current/logstash-core/lib/logstash/pipeline.rb:330:in `start_workers'"]}
```

If i remove `codec => rubydebug` then everything runs fine and i see the message in the log.

```
2017-08-10T17:11:56.234Z 127.0.0.1 hi
```

**Comment by pan1c-us** [comment]
Just an FYI - Same error here.

Ubuntu 14.04 Trusty

LOGSTASH_CORE_VERSION = "5.5.0"

Error from Logs:

[2017-08-11T15:47:22,439][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>32, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>4000}
[2017-08-11T15:47:22,469][INFO ][logstash.pipeline        ] Pipeline main started
[2017-08-11T15:47:22,474][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"0.0.0.0:2055"}
[2017-08-11T15:47:22,498][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-08-11T15:47:22,507][INFO ][logstash.inputs.udp      ] UDP listener started {:address=>"0.0.0.0:2055", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2017-08-11T15:47:23,117][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NameError: undefined local variable or method `dotfile' for #<AwesomePrint::Inspector:0x4822278a>>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:163:in `merge_custom_defaults!'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:50:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:9:in `ai'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:39:in `encode_default'", "org/jruby/RubyMethod.java:120:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:35:in `encode'", "/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:15:in `multi_receive'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:14:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:420:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:419:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:330:in `start_workers'"]}

**Comment by imweijh** [comment]
same problem here 
CentOS 6.9
ELK 5.5.2 from yum repo


```
  if "_grokparsefailure" in [tags] {
    file {
      path => "/var/log/logstash/_grokfail-%{+YYYY.MM.dd}.log"
      codec => rubydebug
    }

```


> [2017-08-25T13:43:45,839][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NameError: undefined local variable or method `dotfile' for #<AwesomePrint::Inspector:0x1e852547>>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:163:in `merge_custom_defaults!'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:50:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:9:in `ai'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:39:in `encode_default'", "org/jruby/RubyMethod.java:120:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:35:in `encode'", "/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:420:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:419:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:330:in `start_workers'"]}

@jakelandis @jordansissel

**Comment by anjo-swe** [comment]
@jakelandis looks like it's solved by https://github.com/awesome-print/awesome_print/issues/316

**Comment by jakelandis** [comment]
I was finally able to reproduce this. 

`unset  HOME` then use stdout with the rubydebug codec. 

I also tested that this PR fixes the crashing : https://github.com/awesome-print/awesome_print/pull/324/files

The workaround until that gets released is ensure that `$HOME` is set for the running environment.

**Comment by tbennett6421** [comment]
Affects me as well.

**Comment by manish2479** [comment]
The real fix for me is to apply this patch which fixed it without setting $HOME.

`https://github.com/awesome-print/awesome_print/pull/324/files`

**Comment by KIVagant** [comment]
Got the same situation when I forgot to turn off stdout rubydebug codec and started the service.

**Comment by davidtinker** [comment]
I added this to /etc/logstash/startup.options:

    # workaround for https://github.com/logstash-plugins/logstash-output-stdout/issues/11
    HOME=${LS_HOME}

then run /usr/share/logstash/bin/system-install

**Comment by m3lixir** [comment]
The above workaround did not work for me on Logstash 6.3 (setting HOME did not fix anything).

Commenting out line 50 (the call to `merge_custom_defaults!`) in `logstash-6.3.0/vendor/bundle/jruby/2.3.0/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb` resolves my issue and I'm able to use the rubydebug codec.

¯\\\_(ツ)_/¯

**Comment by demisx** [comment]
Having the same problem in Logstash 6.3 on Ubuntu 14.04. Commenting out `codec => rubydebug` block made the error go away.

**Comment by joshuar** [comment]
It looks like the upstream issue mentioned here has made it into a newer release of the project.  So is there anything holding back a new release of this plugin to fix this issue?  Or am I misinterpreting the upstream history?
